# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a1771386612ae246464a8b7b4a1f6315edf59844e7e60e0bafe84d94e79261eeec83aa88c549095a36c755a84de125b0035860a417f8b5ec2b4f2907046e08

test:
  secret_key_base: 308c6f44acef1cc1e15541c4887c458d336ad498cb38f3611dffba706b5b151a95f0b94ec042a136cae99affe0855504eac72ca2a341c363fe19e614fe1f6d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
